updated tdm help page
Xilinx/VMC_Help pull request #39
Opened 2024-12-04 12:05 UTC by SrilakshmiDegala

2024-12-04 15:39 UTC, robgraessle approved these changes

2024-12-05 18:41 UTC, abehbood requested changes
This looks so much better than before. Thank you

A key in using this block is how the input to the blocks should be arranged. Right now, this info is mentioned in the comment in the screen shots. But I believe considering its importance, we should explicitly talk about it in the in help. It may get tricky how to explain it for SSR and non SSR cases. 

Also, while we are at it, we should update the screen shots to the latest screen shots.

2024-12-05 19:09 UTC, robgraessle commented
I have updated the screenshots. @SrilakshmiDegala please update the text to describe the input format.

2024-12-09 17:49 UTC, abehbood requested changes
This is nicely done especially the image. 

I am confused about something. Shouldn't we have in the text

**channel 1 data: k1,k2,....kn**

Instead of 

**channel 1 data: k11,k21,....kn1**

Also take a look here to see how to do subscripts in GitHub Markdown. 

https://stackoverflow.com/questions/15155778/superscript-in-markdown-github-flavored

2024-12-10 16:43 UTC, abehbood approved these changes

2024-12-10 21:35 UTC, merged